-- Generated by php tools/schema.php; schema 1.0.0. UTC timestamps, no zero dates.

CREATE TABLE IF NOT EXISTS "#__nicode_form_studio_installation_state" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "state_key" VARCHAR(255) NOT NULL,
    "state_json" TEXT NOT NULL,
    CONSTRAINT "#__nfs_installation_state_u0" UNIQUE ("state_key")
);

CREATE TABLE IF NOT EXISTS "#__nicode_form_studio_forms" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "uuid" CHAR(36) NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "alias" VARCHAR(255) NOT NULL,
    "state" VARCHAR(64) NOT NULL,
    "access" INTEGER NOT NULL,
    "language" VARCHAR(64) NOT NULL,
    "asset_id" BIGINT NULL,
    "created_at" TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    "created_by" BIGINT NOT NULL,
    "modified_at" TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    "modified_by" BIGINT NOT NULL,
    "publish_up" TIMESTAMP(6) WITHOUT TIME ZONE NULL,
    "publish_down" TIMESTAMP(6) WITHOUT TIME ZONE NULL,
    "draft_revision" BIGINT NOT NULL,
    "published_version_id" BIGINT NULL,
    "params" TEXT NOT NULL,
    CONSTRAINT "#__nfs_forms_u0" UNIQUE ("uuid"),
    CONSTRAINT "#__nfs_forms_u1" UNIQUE ("alias")
);
CREATE INDEX IF NOT EXISTS "#__nfs_forms_i0" ON "#__nicode_form_studio_forms" ("state", "modified_at", "id");
CREATE INDEX IF NOT EXISTS "#__nfs_forms_i1" ON "#__nicode_form_studio_forms" ("published_version_id");

CREATE TABLE IF NOT EXISTS "#__nicode_form_studio_elements" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "uuid" CHAR(36) NOT NULL,
    "form_id" BIGINT NOT NULL,
    "parent_uuid" CHAR(36) NULL,
    "element_type" VARCHAR(64) NOT NULL,
    "ordering" INTEGER NOT NULL,
    "properties" TEXT NOT NULL,
    CONSTRAINT "#__nfs_elements_u0" UNIQUE ("form_id", "uuid"),
    CONSTRAINT "#__nfs_elements_form" FOREIGN KEY ("form_id") REFERENCES "#__nicode_form_studio_forms" ("id")
);
CREATE INDEX IF NOT EXISTS "#__nfs_elements_i0" ON "#__nicode_form_studio_elements" ("form_id", "parent_uuid", "ordering");

CREATE TABLE IF NOT EXISTS "#__nicode_form_studio_fields" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "uuid" CHAR(36) NOT NULL,
    "form_id" BIGINT NOT NULL,
    "machine_name" VARCHAR(255) NOT NULL,
    "field_type" VARCHAR(64) NOT NULL,
    "logical_type" VARCHAR(64) NOT NULL,
    "config" TEXT NOT NULL,
    "persist_value" SMALLINT NOT NULL,
    "searchable" SMALLINT NOT NULL,
    "filterable" SMALLINT NOT NULL,
    "sortable" SMALLINT NOT NULL,
    "sensitive" SMALLINT NOT NULL,
    "include_email" SMALLINT NOT NULL,
    "include_export" SMALLINT NOT NULL,
    CONSTRAINT "#__nfs_fields_u0" UNIQUE ("form_id", "uuid"),
    CONSTRAINT "#__nfs_fields_u1" UNIQUE ("form_id", "machine_name"),
    CONSTRAINT "#__nfs_fields_form" FOREIGN KEY ("form_id") REFERENCES "#__nicode_form_studio_forms" ("id")
);

CREATE TABLE IF NOT EXISTS "#__nicode_form_studio_field_options" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "uuid" CHAR(36) NOT NULL,
    "form_id" BIGINT NOT NULL,
    "field_uuid" CHAR(36) NOT NULL,
    "option_value" VARCHAR(255) NOT NULL,
    "label" TEXT NOT NULL,
    "ordering" INTEGER NOT NULL,
    "enabled" SMALLINT NOT NULL,
    "metadata" TEXT NOT NULL,
    CONSTRAINT "#__nfs_field_options_u0" UNIQUE ("form_id", "field_uuid", "option_value"),
    CONSTRAINT "#__nfs_field_options_form" FOREIGN KEY ("form_id") REFERENCES "#__nicode_form_studio_forms" ("id")
);
CREATE INDEX IF NOT EXISTS "#__nfs_field_options_i0" ON "#__nicode_form_studio_field_options" ("form_id", "field_uuid", "ordering");

CREATE TABLE IF NOT EXISTS "#__nicode_form_studio_rules" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "uuid" CHAR(36) NOT NULL,
    "form_id" BIGINT NOT NULL,
    "enabled" SMALLINT NOT NULL,
    "priority" INTEGER NOT NULL,
    CONSTRAINT "#__nfs_rules_u0" UNIQUE ("form_id", "uuid"),
    CONSTRAINT "#__nfs_rules_form" FOREIGN KEY ("form_id") REFERENCES "#__nicode_form_studio_forms" ("id")
);
CREATE INDEX IF NOT EXISTS "#__nfs_rules_i0" ON "#__nicode_form_studio_rules" ("form_id", "priority");

CREATE TABLE IF NOT EXISTS "#__nicode_form_studio_rule_conditions" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "form_id" BIGINT NOT NULL,
    "rule_uuid" CHAR(36) NOT NULL,
    "definition" TEXT NOT NULL,
    CONSTRAINT "#__nfs_rule_conditions_u0" UNIQUE ("form_id", "rule_uuid"),
    CONSTRAINT "#__nfs_rule_conditions_form" FOREIGN KEY ("form_id") REFERENCES "#__nicode_form_studio_forms" ("id")
);

CREATE TABLE IF NOT EXISTS "#__nicode_form_studio_rule_effects" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "form_id" BIGINT NOT NULL,
    "rule_uuid" CHAR(36) NOT NULL,
    "ordering" INTEGER NOT NULL,
    "definition" TEXT NOT NULL,
    CONSTRAINT "#__nfs_rule_effects_u0" UNIQUE ("form_id", "rule_uuid", "ordering"),
    CONSTRAINT "#__nfs_rule_effects_form" FOREIGN KEY ("form_id") REFERENCES "#__nicode_form_studio_forms" ("id")
);

CREATE TABLE IF NOT EXISTS "#__nicode_form_studio_actions" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "uuid" CHAR(36) NOT NULL,
    "form_id" BIGINT NOT NULL,
    "action_type" VARCHAR(64) NOT NULL,
    "enabled" SMALLINT NOT NULL,
    "ordering" INTEGER NOT NULL,
    "condition_spec" TEXT NULL,
    "config" TEXT NOT NULL,
    "failure_policy" VARCHAR(64) NOT NULL,
    "retry_policy" TEXT NOT NULL,
    CONSTRAINT "#__nfs_actions_u0" UNIQUE ("form_id", "uuid"),
    CONSTRAINT "#__nfs_actions_form" FOREIGN KEY ("form_id") REFERENCES "#__nicode_form_studio_forms" ("id")
);
CREATE INDEX IF NOT EXISTS "#__nfs_actions_i0" ON "#__nicode_form_studio_actions" ("form_id", "ordering");

CREATE TABLE IF NOT EXISTS "#__nicode_form_studio_option_sets" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "uuid" CHAR(36) NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "revision" BIGINT NOT NULL,
    "modified_at" TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    "modified_by" BIGINT NOT NULL,
    CONSTRAINT "#__nfs_option_sets_u0" UNIQUE ("uuid")
);

CREATE TABLE IF NOT EXISTS "#__nicode_form_studio_option_set_versions" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "option_set_id" BIGINT NOT NULL,
    "revision" BIGINT NOT NULL,
    "snapshot" TEXT NOT NULL,
    "hash" CHAR(64) NOT NULL,
    "created_at" TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    "created_by" BIGINT NOT NULL,
    CONSTRAINT "#__nfs_option_set_versions_u0" UNIQUE ("option_set_id", "revision")
);

CREATE TABLE IF NOT EXISTS "#__nicode_form_studio_option_set_items" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "option_set_id" BIGINT NOT NULL,
    "uuid" CHAR(36) NOT NULL,
    "option_value" VARCHAR(255) NOT NULL,
    "label" TEXT NOT NULL,
    "ordering" INTEGER NOT NULL,
    "enabled" SMALLINT NOT NULL,
    "metadata" TEXT NOT NULL,
    CONSTRAINT "#__nfs_option_set_items_u0" UNIQUE ("option_set_id", "option_value")
);
CREATE INDEX IF NOT EXISTS "#__nfs_option_set_items_i0" ON "#__nicode_form_studio_option_set_items" ("option_set_id", "ordering");

CREATE TABLE IF NOT EXISTS "#__nicode_form_studio_data_sources" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "uuid" CHAR(36) NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "provider" VARCHAR(64) NOT NULL,
    "provider_version" VARCHAR(64) NOT NULL,
    "config" TEXT NOT NULL,
    "enabled" SMALLINT NOT NULL,
    "revision" BIGINT NOT NULL,
    CONSTRAINT "#__nfs_data_sources_u0" UNIQUE ("uuid")
);

CREATE TABLE IF NOT EXISTS "#__nicode_form_studio_email_templates" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "uuid" CHAR(36) NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "language" VARCHAR(64) NOT NULL,
    "subject" TEXT NOT NULL,
    "body_html" TEXT NOT NULL,
    "body_text" TEXT NOT NULL,
    "revision" BIGINT NOT NULL,
    CONSTRAINT "#__nfs_email_templates_u0" UNIQUE ("uuid")
);

CREATE TABLE IF NOT EXISTS "#__nicode_form_studio_form_templates" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "uuid" CHAR(36) NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "definition" TEXT NOT NULL,
    "revision" BIGINT NOT NULL,
    CONSTRAINT "#__nfs_form_templates_u0" UNIQUE ("uuid")
);

CREATE TABLE IF NOT EXISTS "#__nicode_form_studio_translations" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "form_id" BIGINT NOT NULL,
    "entity_uuid" CHAR(36) NOT NULL,
    "language" VARCHAR(64) NOT NULL,
    "property_name" VARCHAR(64) NOT NULL,
    "translated_value" TEXT NOT NULL,
    CONSTRAINT "#__nfs_translations_u0" UNIQUE ("form_id", "entity_uuid", "language", "property_name"),
    CONSTRAINT "#__nfs_translations_form" FOREIGN KEY ("form_id") REFERENCES "#__nicode_form_studio_forms" ("id")
);

CREATE TABLE IF NOT EXISTS "#__nicode_form_studio_form_versions" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "form_id" BIGINT NOT NULL,
    "revision" BIGINT NOT NULL,
    "schema_version" VARCHAR(64) NOT NULL,
    "spec" TEXT NOT NULL,
    "hash" CHAR(64) NOT NULL,
    "published_at" TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    "published_by" BIGINT NOT NULL,
    "comment" TEXT NOT NULL,
    "revoked_at" TIMESTAMP(6) WITHOUT TIME ZONE NULL,
    CONSTRAINT "#__nfs_form_versions_u0" UNIQUE ("form_id", "revision"),
    CONSTRAINT "#__nfs_form_versions_form" FOREIGN KEY ("form_id") REFERENCES "#__nicode_form_studio_forms" ("id")
);

CREATE TABLE IF NOT EXISTS "#__nicode_form_studio_version_field_policy" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "form_id" BIGINT NOT NULL,
    "form_version_id" BIGINT NOT NULL,
    "field_uuid" CHAR(36) NOT NULL,
    "sensitive" SMALLINT NOT NULL,
    "indexed" SMALLINT NOT NULL,
    CONSTRAINT "#__nfs_version_field_policy_u0" UNIQUE ("form_version_id", "field_uuid"),
    CONSTRAINT "#__nfs_version_field_policy_form" FOREIGN KEY ("form_id") REFERENCES "#__nicode_form_studio_forms" ("id")
);
CREATE INDEX IF NOT EXISTS "#__nfs_version_field_policy_i0" ON "#__nicode_form_studio_version_field_policy" ("form_id", "field_uuid", "sensitive", "form_version_id");

CREATE TABLE IF NOT EXISTS "#__nicode_form_studio_submissions" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "uuid" CHAR(36) NOT NULL,
    "form_id" BIGINT NOT NULL,
    "form_version_id" BIGINT NOT NULL,
    "state" VARCHAR(64) NOT NULL,
    "received_at" TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    "processed_at" TIMESTAMP(6) WITHOUT TIME ZONE NULL,
    "user_id" BIGINT NULL,
    "channel" VARCHAR(64) NOT NULL,
    "locale" VARCHAR(64) NOT NULL,
    "canonical_payload" TEXT NOT NULL,
    "payload_schema_version" VARCHAR(64) NOT NULL,
    "action_status" VARCHAR(64) NOT NULL,
    "expires_at" TIMESTAMP(6) WITHOUT TIME ZONE NULL,
    "anonymized_at" TIMESTAMP(6) WITHOUT TIME ZONE NULL,
    "attempt_hash" CHAR(64) NOT NULL,
    "index_pending" SMALLINT NOT NULL,
    CONSTRAINT "#__nfs_submissions_u0" UNIQUE ("uuid"),
    CONSTRAINT "#__nfs_submissions_u1" UNIQUE ("form_id", "attempt_hash"),
    CONSTRAINT "#__nfs_submissions_form" FOREIGN KEY ("form_id") REFERENCES "#__nicode_form_studio_forms" ("id")
);
CREATE INDEX IF NOT EXISTS "#__nfs_submissions_i0" ON "#__nicode_form_studio_submissions" ("received_at", "id");
CREATE INDEX IF NOT EXISTS "#__nfs_submissions_i1" ON "#__nicode_form_studio_submissions" ("form_id", "received_at", "id");
CREATE INDEX IF NOT EXISTS "#__nfs_submissions_i2" ON "#__nicode_form_studio_submissions" ("form_id", "state", "received_at", "id");
CREATE INDEX IF NOT EXISTS "#__nfs_submissions_i3" ON "#__nicode_form_studio_submissions" ("form_version_id", "received_at", "id");
CREATE INDEX IF NOT EXISTS "#__nfs_submissions_i4" ON "#__nicode_form_studio_submissions" ("user_id", "received_at", "id");
CREATE INDEX IF NOT EXISTS "#__nfs_submissions_i5" ON "#__nicode_form_studio_submissions" ("action_status", "received_at", "id");
CREATE INDEX IF NOT EXISTS "#__nfs_submissions_i6" ON "#__nicode_form_studio_submissions" ("expires_at", "id");
CREATE INDEX IF NOT EXISTS "#__nfs_submissions_i7" ON "#__nicode_form_studio_submissions" ("index_pending", "id");
CREATE INDEX IF NOT EXISTS "#__nfs_submissions_i8" ON "#__nicode_form_studio_submissions" ("form_id", "id");

CREATE TABLE IF NOT EXISTS "#__nicode_form_studio_submission_index" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "submission_id" BIGINT NOT NULL,
    "form_id" BIGINT NOT NULL,
    "form_version_id" BIGINT NOT NULL,
    "field_uuid" CHAR(36) NOT NULL,
    "instance_path" VARCHAR(4735) NOT NULL DEFAULT '',
    "instance_hash" CHAR(64) NOT NULL DEFAULT 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    "value_type" VARCHAR(64) NOT NULL,
    "value_keyword" VARCHAR(255) NULL,
    "value_text" TEXT NULL,
    "value_integer" BIGINT NULL,
    "value_decimal" DECIMAL(38,12) NULL,
    "value_boolean" SMALLINT NULL,
    "value_date" DATE NULL,
    "value_datetime" TIMESTAMP(6) WITHOUT TIME ZONE NULL,
    "ordinal" INTEGER NOT NULL,
    CONSTRAINT "#__nfs_submission_index_u0" UNIQUE ("submission_id", "field_uuid", "instance_hash", "ordinal"),
    CONSTRAINT "#__nfs_submission_index_sub" FOREIGN KEY ("submission_id") REFERENCES "#__nicode_form_studio_submissions" ("id")
);
CREATE INDEX IF NOT EXISTS "#__nfs_submission_index_i0" ON "#__nicode_form_studio_submission_index" ("form_id", "field_uuid", "value_keyword", "submission_id");
CREATE INDEX IF NOT EXISTS "#__nfs_submission_index_i1" ON "#__nicode_form_studio_submission_index" ("form_id", "field_uuid", "value_integer", "submission_id");
CREATE INDEX IF NOT EXISTS "#__nfs_submission_index_i2" ON "#__nicode_form_studio_submission_index" ("form_id", "field_uuid", "value_decimal", "submission_id");
CREATE INDEX IF NOT EXISTS "#__nfs_submission_index_i3" ON "#__nicode_form_studio_submission_index" ("form_id", "field_uuid", "value_boolean", "submission_id");
CREATE INDEX IF NOT EXISTS "#__nfs_submission_index_i4" ON "#__nicode_form_studio_submission_index" ("form_id", "field_uuid", "value_date", "submission_id");
CREATE INDEX IF NOT EXISTS "#__nfs_submission_index_i5" ON "#__nicode_form_studio_submission_index" ("form_id", "field_uuid", "value_datetime", "submission_id");

CREATE TABLE IF NOT EXISTS "#__nicode_form_studio_submission_files" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "uuid" CHAR(36) NOT NULL,
    "submission_id" BIGINT NOT NULL,
    "field_uuid" CHAR(36) NOT NULL,
    "instance_path" VARCHAR(4735) NOT NULL DEFAULT '',
    "instance_hash" CHAR(64) NOT NULL DEFAULT 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    "provider" VARCHAR(64) NOT NULL,
    "storage_key" VARCHAR(255) NOT NULL,
    "original_name" VARCHAR(255) NOT NULL,
    "mime" VARCHAR(255) NOT NULL,
    "size_bytes" BIGINT NOT NULL,
    "checksum" CHAR(64) NOT NULL,
    "created_at" TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT "#__nfs_submission_files_u0" UNIQUE ("uuid"),
    CONSTRAINT "#__nfs_submission_files_u1" UNIQUE ("provider", "storage_key"),
    CONSTRAINT "#__nfs_submission_files_sub" FOREIGN KEY ("submission_id") REFERENCES "#__nicode_form_studio_submissions" ("id")
);
CREATE INDEX IF NOT EXISTS "#__nfs_submission_files_i0" ON "#__nicode_form_studio_submission_files" ("submission_id");

CREATE TABLE IF NOT EXISTS "#__nicode_form_studio_upload_staging" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "form_id" BIGINT NOT NULL,
    "provider" VARCHAR(64) NOT NULL,
    "storage_key" VARCHAR(255) NOT NULL,
    "owner_token" CHAR(64) NOT NULL,
    "state" VARCHAR(64) NOT NULL,
    "created_at" TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    "expires_at" TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    "size_bytes" BIGINT NULL,
    "checksum" CHAR(64) NULL,
    CONSTRAINT "#__nfs_upload_staging_u0" UNIQUE ("provider", "storage_key")
);
CREATE INDEX IF NOT EXISTS "#__nfs_upload_staging_i0" ON "#__nicode_form_studio_upload_staging" ("expires_at", "id");
CREATE INDEX IF NOT EXISTS "#__nfs_upload_staging_i1" ON "#__nicode_form_studio_upload_staging" ("form_id", "id");

CREATE TABLE IF NOT EXISTS "#__nicode_form_studio_action_runs" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "submission_id" BIGINT NOT NULL,
    "action_uuid" CHAR(36) NOT NULL,
    "action_type" VARCHAR(64) NOT NULL,
    "attempt" INTEGER NOT NULL,
    "state" VARCHAR(64) NOT NULL,
    "created_at" TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    "started_at" TIMESTAMP(6) WITHOUT TIME ZONE NULL,
    "finished_at" TIMESTAMP(6) WITHOUT TIME ZONE NULL,
    "result_code" VARCHAR(64) NULL,
    "next_retry_at" TIMESTAMP(6) WITHOUT TIME ZONE NULL,
    "lease_token" CHAR(64) NULL,
    "lease_until" TIMESTAMP(6) WITHOUT TIME ZONE NULL,
    "revision" BIGINT NOT NULL,
    CONSTRAINT "#__nfs_action_runs_u0" UNIQUE ("submission_id", "action_uuid", "attempt"),
    CONSTRAINT "#__nfs_action_runs_sub" FOREIGN KEY ("submission_id") REFERENCES "#__nicode_form_studio_submissions" ("id")
);
CREATE INDEX IF NOT EXISTS "#__nfs_action_runs_i0" ON "#__nicode_form_studio_action_runs" ("state", "next_retry_at", "id");
CREATE INDEX IF NOT EXISTS "#__nfs_action_runs_i1" ON "#__nicode_form_studio_action_runs" ("submission_id", "id");
CREATE INDEX IF NOT EXISTS "#__nfs_action_runs_i2" ON "#__nicode_form_studio_action_runs" ("created_at", "id");

CREATE TABLE IF NOT EXISTS "#__nicode_form_studio_submission_notes" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "submission_id" BIGINT NOT NULL,
    "created_by" BIGINT NOT NULL,
    "created_at" TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    "body" TEXT NOT NULL,
    CONSTRAINT "#__nfs_submission_notes_sub" FOREIGN KEY ("submission_id") REFERENCES "#__nicode_form_studio_submissions" ("id")
);
CREATE INDEX IF NOT EXISTS "#__nfs_submission_notes_i0" ON "#__nicode_form_studio_submission_notes" ("submission_id", "id");

CREATE TABLE IF NOT EXISTS "#__nicode_form_studio_technical_log" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "correlation_id" CHAR(36) NOT NULL,
    "level" VARCHAR(64) NOT NULL,
    "event_type" VARCHAR(64) NOT NULL,
    "form_uuid" CHAR(36) NULL,
    "version_id" BIGINT NULL,
    "submission_uuid" CHAR(36) NULL,
    "action_run_id" BIGINT NULL,
    "job_id" BIGINT NULL,
    "created_at" TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL
);
CREATE INDEX IF NOT EXISTS "#__nfs_technical_log_i0" ON "#__nicode_form_studio_technical_log" ("created_at", "id");
CREATE INDEX IF NOT EXISTS "#__nfs_technical_log_i1" ON "#__nicode_form_studio_technical_log" ("correlation_id", "id");
CREATE INDEX IF NOT EXISTS "#__nfs_technical_log_i2" ON "#__nicode_form_studio_technical_log" ("level", "id");

CREATE TABLE IF NOT EXISTS "#__nicode_form_studio_audit_log" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "correlation_id" CHAR(36) NOT NULL,
    "actor_id" BIGINT NOT NULL,
    "event_type" VARCHAR(64) NOT NULL,
    "form_id" BIGINT NULL,
    "submission_uuid" CHAR(36) NULL,
    "created_at" TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    "safe_metadata" TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS "#__nfs_audit_log_i0" ON "#__nicode_form_studio_audit_log" ("form_id", "created_at", "id");
CREATE INDEX IF NOT EXISTS "#__nfs_audit_log_i1" ON "#__nicode_form_studio_audit_log" ("event_type", "created_at", "id");
CREATE INDEX IF NOT EXISTS "#__nfs_audit_log_i2" ON "#__nicode_form_studio_audit_log" ("form_id", "submission_uuid", "id");
CREATE INDEX IF NOT EXISTS "#__nfs_audit_log_i3" ON "#__nicode_form_studio_audit_log" ("created_at", "id");

CREATE TABLE IF NOT EXISTS "#__nicode_form_studio_jobs" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "uuid" CHAR(36) NOT NULL,
    "job_type" VARCHAR(64) NOT NULL,
    "form_id" BIGINT NULL,
    "creator_id" BIGINT NOT NULL,
    "state" VARCHAR(64) NOT NULL,
    "parameters" TEXT NOT NULL,
    "cursor_data" TEXT NOT NULL,
    "processed" BIGINT NOT NULL,
    "failed" BIGINT NOT NULL,
    "created_at" TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    "started_at" TIMESTAMP(6) WITHOUT TIME ZONE NULL,
    "finished_at" TIMESTAMP(6) WITHOUT TIME ZONE NULL,
    "available_at" TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    "lease_token" CHAR(64) NULL,
    "lease_until" TIMESTAMP(6) WITHOUT TIME ZONE NULL,
    "revision" BIGINT NOT NULL,
    "result_code" VARCHAR(64) NULL,
    "artifact_key" VARCHAR(255) NULL,
    "expires_at" TIMESTAMP(6) WITHOUT TIME ZONE NULL,
    CONSTRAINT "#__nfs_jobs_u0" UNIQUE ("uuid")
);
CREATE INDEX IF NOT EXISTS "#__nfs_jobs_i0" ON "#__nicode_form_studio_jobs" ("state", "available_at", "id");
CREATE INDEX IF NOT EXISTS "#__nfs_jobs_i1" ON "#__nicode_form_studio_jobs" ("lease_until", "id");
CREATE INDEX IF NOT EXISTS "#__nfs_jobs_i2" ON "#__nicode_form_studio_jobs" ("creator_id", "created_at", "id");
CREATE INDEX IF NOT EXISTS "#__nfs_jobs_i3" ON "#__nicode_form_studio_jobs" ("form_id", "job_type", "state", "id");
CREATE INDEX IF NOT EXISTS "#__nfs_jobs_i4" ON "#__nicode_form_studio_jobs" ("job_type", "id");

CREATE TABLE IF NOT EXISTS "#__nicode_form_studio_saved_views" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "uuid" CHAR(36) NOT NULL,
    "owner_id" BIGINT NOT NULL,
    "form_id" BIGINT NULL,
    "name" VARCHAR(255) NOT NULL,
    "shared" SMALLINT NOT NULL,
    "query_spec" TEXT NOT NULL,
    "columns_spec" TEXT NOT NULL,
    "sort_spec" TEXT NOT NULL,
    CONSTRAINT "#__nfs_saved_views_u0" UNIQUE ("uuid")
);
CREATE INDEX IF NOT EXISTS "#__nfs_saved_views_i0" ON "#__nicode_form_studio_saved_views" ("owner_id", "form_id");

CREATE TABLE IF NOT EXISTS "#__nicode_form_studio_rate_limits" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "scope_hash" CHAR(64) NOT NULL,
    "window_start" TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    "expires_at" TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    "attempts" BIGINT NOT NULL,
    CONSTRAINT "#__nfs_rate_limits_u0" UNIQUE ("scope_hash", "window_start")
);
CREATE INDEX IF NOT EXISTS "#__nfs_rate_limits_i0" ON "#__nicode_form_studio_rate_limits" ("expires_at");

CREATE TABLE IF NOT EXISTS "#__nicode_form_studio_attempts" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "attempt_hash" CHAR(64) NOT NULL,
    "form_id" BIGINT NOT NULL,
    "form_version_id" BIGINT NOT NULL,
    "request_hash" CHAR(64) NOT NULL,
    "state" VARCHAR(64) NOT NULL,
    "response" TEXT NULL,
    "submission_uuid" CHAR(36) NULL,
    "created_at" TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    "expires_at" TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT "#__nfs_attempts_u0" UNIQUE ("form_id", "attempt_hash")
);
CREATE INDEX IF NOT EXISTS "#__nfs_attempts_i0" ON "#__nicode_form_studio_attempts" ("expires_at");
