<?php
declare(strict_types=1);
$api('optionset.create', expected: 405);
$api('optionset.create', ['name' => 'Forbidden without CSRF'], expected: 403, csrf: false);
$setId = $api('optionset.create', ['name' => 'HTTP shared choices'])['id'];
$optionRows = [['value' => 'ES', 'label' => 'Spain', 'default' => true], ['value' => 'FR', 'label' => 'France']];
$assert($api('optionset.save', ['id' => $setId, 'revision' => 0, 'name' => 'HTTP shared choices', 'options' => $optionRows])['revision'] === 1, 'Shared resource revision not advanced.');
$api('optionset.save', ['id' => $setId, 'revision' => 0, 'name' => 'Stale overwrite', 'options' => $optionRows], expected: 409);
$resourcePage = $request($base . '?option=com_nicode_form_studio&view=optionset&id=' . $setId);
$assert($resourcePage['status'] === 200 && str_contains($resourcePage['body'], 'data-nfs-resource-data') && !str_contains($resourcePage['body'], '>COM_NICODE_FORM_STUDIO_RESOURCE_'), 'Option resource editor or translations missing.');
$resourceList = $request($base . '?option=com_nicode_form_studio&view=resources');
$assert($resourceList['status'] === 200 && str_contains($resourceList['body'], 'HTTP shared choices'), 'Native shared resource list missing.');
$source = $api('optionset.source', ['id' => $setId, 'revision' => 1]);
$resourceForm = $api('create', ['name' => 'Pinned choices HTTP fixture', 'alias' => 'pinned-http-' . bin2hex(random_bytes(6))]);
$resourceEdit = $api('record', query: ['id' => $resourceForm['id']]);
$catalogue = $api('source.categories', query: ['id' => $resourceForm['id']]);
$assert(count($catalogue['rows']) > 0 && count($catalogue['rows']) <= 100, 'Native category catalogue missing or unbounded.');
$selectedCategory = (int) $catalogue['rows'][0]['id'];
$selectedCatalogue = $api('source.categories', query: ['id' => $resourceForm['id'], 'ids' => [$selectedCategory]]);
$assert(array_map('intval', array_column($selectedCatalogue['rows'], 'id')) === [$selectedCategory], 'Selected category title resolution returned a different scope.');
$api('source.categories', query: ['id' => $resourceForm['id'], 'ids' => ['1junk']], expected: 422);
$api('source.categories', query: ['id' => $resourceForm['id'], 'before' => '1junk'], expected: 422);
$api('source.categories', query: ['id' => $resourceForm['id'], 'search' => str_repeat('x', 101)], expected: 422);
$api('source.categories', ['id' => $resourceForm['id']], expected: 405);
$none = $api('source.categories', query: ['id' => $resourceForm['id'], 'search' => 'no-source-category-' . bin2hex(random_bytes(12))]);
$assert($none['rows'] === [] && $none['next_before'] === null, 'Category search ignored its filter.');
$resourceDraft = $resourceEdit['draft'];
$choiceUuid = '58fbc5e7-b13a-4468-9d92-d62c3d833f73';
$resourceDraft['elements'] = [['uuid' => $choiceUuid, 'type' => 'field', 'parent_uuid' => null]];
$resourceDraft['fields'] = [['uuid' => $choiceUuid, 'name' => 'country', 'type' => 'select', 'config' => ['label' => 'Country'], 'source' => $source]];
$api('save', ['id' => $resourceForm['id'], 'revision' => 0, 'draft' => $resourceDraft]);
$resourcePublished = $api('publish', ['id' => $resourceForm['id'], 'revision' => 1]);
$oldPreview = $api('preview', query: ['id' => $resourceForm['id'], 'version' => $resourcePublished['version_id']]);
$assert(str_contains($oldPreview['html'], 'Spain'), 'Published source options not rendered.');
$assert($dom($oldPreview['html'])->query('//option[@value="ES" and @selected]')->length === 1, 'Shared option default not applied in native preview.');
$api('optionset.record', query: ['id' => $setId, 'revision' => '1junk'], expected: 422);
$optionRows[0]['label'] = 'Changed resource label';
$api('optionset.save', ['id' => $setId, 'revision' => 1, 'name' => 'Edited HTTP choices', 'options' => $optionRows]);
$oldRecord = $api('optionset.record', query: ['id' => $setId, 'revision' => 1]);
$assert($oldRecord['snapshot']['options'][0]['label'] === 'Spain', 'Historical resource revised in place.');
$newPreview = $api('preview', query: ['id' => $resourceForm['id'], 'version' => $resourcePublished['version_id']]);
$assert(str_contains($newPreview['html'], 'Spain') && !str_contains($newPreview['html'], 'Changed resource label'), 'Published form followed mutable resource.');
$provinceSet = $api('optionset.create', ['name' => 'HTTP dependent choices'])['id'];
$api('optionset.save', ['id' => $provinceSet, 'revision' => 0, 'name' => 'HTTP dependent choices', 'options' => [['value' => 'MD', 'label' => 'Madrid', 'when' => ['country' => 'ES']]]]);
$api('optionset.source', ['id' => $provinceSet, 'revision' => 1], expected: 422);
$bound = $api('optionset.source', ['id' => $provinceSet, 'revision' => 1, 'bindings' => ['country' => $choiceUuid]]);
$assert($bound['dependencies'] === [$choiceUuid] && $bound['config']['options'][0]['when'][$choiceUuid] === 'ES', 'Portable dependency parameter not bound to field.');
file_put_contents($root . '/build/admin-optionsets-results.json', json_encode(['passed' => true, 'timestamp' => gmdate(DATE_ATOM), 'resource_id' => $setId, 'dependent_resource_id' => $provinceSet, 'form_id' => $resourceForm['id'], 'checks' => ['native views', 'CSRF and HTTP method', 'optimistic conflict', 'immutable revisions', 'published form snapshot isolation', 'dependency binding']], JSON_PRETTY_PRINT | JSON_THROW_ON_ERROR));
echo "Native options HTTP: resources, CSRF, conflicts, immutable published snapshot and dependency bindings passed.\n";
