-- Generated by php tools/schema.php; schema 1.0.0. UTC timestamps, no zero dates.

CREATE TABLE IF NOT EXISTS `#__nicode_form_studio_installation_state` (
    `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `state_key` VARCHAR(255) NOT NULL,
    `state_json` LONGTEXT NOT NULL,
    CONSTRAINT `nfs_installation_state_u0` UNIQUE (`state_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `#__nicode_form_studio_forms` (
    `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `uuid` CHAR(36) NOT NULL,
    `name` VARCHAR(255) NOT NULL,
    `alias` VARCHAR(255) NOT NULL,
    `state` VARCHAR(64) NOT NULL,
    `access` INTEGER NOT NULL,
    `language` VARCHAR(64) NOT NULL,
    `asset_id` BIGINT NULL,
    `created_at` DATETIME(6) NOT NULL,
    `created_by` BIGINT NOT NULL,
    `modified_at` DATETIME(6) NOT NULL,
    `modified_by` BIGINT NOT NULL,
    `publish_up` DATETIME(6) NULL,
    `publish_down` DATETIME(6) NULL,
    `draft_revision` BIGINT NOT NULL,
    `published_version_id` BIGINT NULL,
    `params` LONGTEXT NOT NULL,
    CONSTRAINT `nfs_forms_u0` UNIQUE (`uuid`),
    CONSTRAINT `nfs_forms_u1` UNIQUE (`alias`),
    INDEX `nfs_forms_i0` (`state`, `modified_at`, `id`),
    INDEX `nfs_forms_i1` (`published_version_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `#__nicode_form_studio_elements` (
    `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `uuid` CHAR(36) NOT NULL,
    `form_id` BIGINT NOT NULL,
    `parent_uuid` CHAR(36) NULL,
    `element_type` VARCHAR(64) NOT NULL,
    `ordering` INTEGER NOT NULL,
    `properties` LONGTEXT NOT NULL,
    CONSTRAINT `nfs_elements_u0` UNIQUE (`form_id`, `uuid`),
    CONSTRAINT `#__nfs_elements_form` FOREIGN KEY (`form_id`) REFERENCES `#__nicode_form_studio_forms` (`id`),
    INDEX `nfs_elements_i0` (`form_id`, `parent_uuid`, `ordering`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `#__nicode_form_studio_fields` (
    `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `uuid` CHAR(36) NOT NULL,
    `form_id` BIGINT NOT NULL,
    `machine_name` VARCHAR(255) NOT NULL,
    `field_type` VARCHAR(64) NOT NULL,
    `logical_type` VARCHAR(64) NOT NULL,
    `config` LONGTEXT NOT NULL,
    `persist_value` SMALLINT NOT NULL,
    `searchable` SMALLINT NOT NULL,
    `filterable` SMALLINT NOT NULL,
    `sortable` SMALLINT NOT NULL,
    `sensitive` SMALLINT NOT NULL,
    `include_email` SMALLINT NOT NULL,
    `include_export` SMALLINT NOT NULL,
    CONSTRAINT `nfs_fields_u0` UNIQUE (`form_id`, `uuid`),
    CONSTRAINT `nfs_fields_u1` UNIQUE (`form_id`, `machine_name`),
    CONSTRAINT `#__nfs_fields_form` FOREIGN KEY (`form_id`) REFERENCES `#__nicode_form_studio_forms` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `#__nicode_form_studio_field_options` (
    `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `uuid` CHAR(36) NOT NULL,
    `form_id` BIGINT NOT NULL,
    `field_uuid` CHAR(36) NOT NULL,
    `option_value` VARBINARY(1020) NOT NULL,
    `label` LONGTEXT NOT NULL,
    `ordering` INTEGER NOT NULL,
    `enabled` SMALLINT NOT NULL,
    `metadata` LONGTEXT NOT NULL,
    CONSTRAINT `nfs_field_options_u0` UNIQUE (`form_id`, `field_uuid`, `option_value`),
    CONSTRAINT `#__nfs_field_options_form` FOREIGN KEY (`form_id`) REFERENCES `#__nicode_form_studio_forms` (`id`),
    INDEX `nfs_field_options_i0` (`form_id`, `field_uuid`, `ordering`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `#__nicode_form_studio_rules` (
    `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `uuid` CHAR(36) NOT NULL,
    `form_id` BIGINT NOT NULL,
    `enabled` SMALLINT NOT NULL,
    `priority` INTEGER NOT NULL,
    CONSTRAINT `nfs_rules_u0` UNIQUE (`form_id`, `uuid`),
    CONSTRAINT `#__nfs_rules_form` FOREIGN KEY (`form_id`) REFERENCES `#__nicode_form_studio_forms` (`id`),
    INDEX `nfs_rules_i0` (`form_id`, `priority`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `#__nicode_form_studio_rule_conditions` (
    `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `form_id` BIGINT NOT NULL,
    `rule_uuid` CHAR(36) NOT NULL,
    `definition` LONGTEXT NOT NULL,
    CONSTRAINT `nfs_rule_conditions_u0` UNIQUE (`form_id`, `rule_uuid`),
    CONSTRAINT `#__nfs_rule_conditions_form` FOREIGN KEY (`form_id`) REFERENCES `#__nicode_form_studio_forms` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `#__nicode_form_studio_rule_effects` (
    `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `form_id` BIGINT NOT NULL,
    `rule_uuid` CHAR(36) NOT NULL,
    `ordering` INTEGER NOT NULL,
    `definition` LONGTEXT NOT NULL,
    CONSTRAINT `nfs_rule_effects_u0` UNIQUE (`form_id`, `rule_uuid`, `ordering`),
    CONSTRAINT `#__nfs_rule_effects_form` FOREIGN KEY (`form_id`) REFERENCES `#__nicode_form_studio_forms` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `#__nicode_form_studio_actions` (
    `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `uuid` CHAR(36) NOT NULL,
    `form_id` BIGINT NOT NULL,
    `action_type` VARCHAR(64) NOT NULL,
    `enabled` SMALLINT NOT NULL,
    `ordering` INTEGER NOT NULL,
    `condition_spec` LONGTEXT NULL,
    `config` LONGTEXT NOT NULL,
    `failure_policy` VARCHAR(64) NOT NULL,
    `retry_policy` LONGTEXT NOT NULL,
    CONSTRAINT `nfs_actions_u0` UNIQUE (`form_id`, `uuid`),
    CONSTRAINT `#__nfs_actions_form` FOREIGN KEY (`form_id`) REFERENCES `#__nicode_form_studio_forms` (`id`),
    INDEX `nfs_actions_i0` (`form_id`, `ordering`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `#__nicode_form_studio_option_sets` (
    `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `uuid` CHAR(36) NOT NULL,
    `name` VARCHAR(255) NOT NULL,
    `revision` BIGINT NOT NULL,
    `modified_at` DATETIME(6) NOT NULL,
    `modified_by` BIGINT NOT NULL,
    CONSTRAINT `nfs_option_sets_u0` UNIQUE (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `#__nicode_form_studio_option_set_versions` (
    `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `option_set_id` BIGINT NOT NULL,
    `revision` BIGINT NOT NULL,
    `snapshot` LONGTEXT NOT NULL,
    `hash` CHAR(64) NOT NULL,
    `created_at` DATETIME(6) NOT NULL,
    `created_by` BIGINT NOT NULL,
    CONSTRAINT `nfs_option_set_versions_u0` UNIQUE (`option_set_id`, `revision`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `#__nicode_form_studio_option_set_items` (
    `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `option_set_id` BIGINT NOT NULL,
    `uuid` CHAR(36) NOT NULL,
    `option_value` VARBINARY(1020) NOT NULL,
    `label` LONGTEXT NOT NULL,
    `ordering` INTEGER NOT NULL,
    `enabled` SMALLINT NOT NULL,
    `metadata` LONGTEXT NOT NULL,
    CONSTRAINT `nfs_option_set_items_u0` UNIQUE (`option_set_id`, `option_value`),
    INDEX `nfs_option_set_items_i0` (`option_set_id`, `ordering`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `#__nicode_form_studio_data_sources` (
    `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `uuid` CHAR(36) NOT NULL,
    `name` VARCHAR(255) NOT NULL,
    `provider` VARCHAR(64) NOT NULL,
    `provider_version` VARCHAR(64) NOT NULL,
    `config` LONGTEXT NOT NULL,
    `enabled` SMALLINT NOT NULL,
    `revision` BIGINT NOT NULL,
    CONSTRAINT `nfs_data_sources_u0` UNIQUE (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `#__nicode_form_studio_email_templates` (
    `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `uuid` CHAR(36) NOT NULL,
    `name` VARCHAR(255) NOT NULL,
    `language` VARCHAR(64) NOT NULL,
    `subject` LONGTEXT NOT NULL,
    `body_html` LONGTEXT NOT NULL,
    `body_text` LONGTEXT NOT NULL,
    `revision` BIGINT NOT NULL,
    CONSTRAINT `nfs_email_templates_u0` UNIQUE (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `#__nicode_form_studio_form_templates` (
    `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `uuid` CHAR(36) NOT NULL,
    `name` VARCHAR(255) NOT NULL,
    `definition` LONGTEXT NOT NULL,
    `revision` BIGINT NOT NULL,
    CONSTRAINT `nfs_form_templates_u0` UNIQUE (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `#__nicode_form_studio_translations` (
    `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `form_id` BIGINT NOT NULL,
    `entity_uuid` CHAR(36) NOT NULL,
    `language` VARCHAR(64) NOT NULL,
    `property_name` VARCHAR(64) NOT NULL,
    `translated_value` LONGTEXT NOT NULL,
    CONSTRAINT `nfs_translations_u0` UNIQUE (`form_id`, `entity_uuid`, `language`, `property_name`),
    CONSTRAINT `#__nfs_translations_form` FOREIGN KEY (`form_id`) REFERENCES `#__nicode_form_studio_forms` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `#__nicode_form_studio_form_versions` (
    `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `form_id` BIGINT NOT NULL,
    `revision` BIGINT NOT NULL,
    `schema_version` VARCHAR(64) NOT NULL,
    `spec` LONGTEXT NOT NULL,
    `hash` CHAR(64) NOT NULL,
    `published_at` DATETIME(6) NOT NULL,
    `published_by` BIGINT NOT NULL,
    `comment` LONGTEXT NOT NULL,
    `revoked_at` DATETIME(6) NULL,
    CONSTRAINT `nfs_form_versions_u0` UNIQUE (`form_id`, `revision`),
    CONSTRAINT `#__nfs_form_versions_form` FOREIGN KEY (`form_id`) REFERENCES `#__nicode_form_studio_forms` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `#__nicode_form_studio_version_field_policy` (
    `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `form_id` BIGINT NOT NULL,
    `form_version_id` BIGINT NOT NULL,
    `field_uuid` CHAR(36) NOT NULL,
    `sensitive` SMALLINT NOT NULL,
    `indexed` SMALLINT NOT NULL,
    CONSTRAINT `nfs_version_field_policy_u0` UNIQUE (`form_version_id`, `field_uuid`),
    CONSTRAINT `#__nfs_version_field_policy_form` FOREIGN KEY (`form_id`) REFERENCES `#__nicode_form_studio_forms` (`id`),
    INDEX `nfs_version_field_policy_i0` (`form_id`, `field_uuid`, `sensitive`, `form_version_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `#__nicode_form_studio_submissions` (
    `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `uuid` CHAR(36) NOT NULL,
    `form_id` BIGINT NOT NULL,
    `form_version_id` BIGINT NOT NULL,
    `state` VARCHAR(64) NOT NULL,
    `received_at` DATETIME(6) NOT NULL,
    `processed_at` DATETIME(6) NULL,
    `user_id` BIGINT NULL,
    `channel` VARCHAR(64) NOT NULL,
    `locale` VARCHAR(64) NOT NULL,
    `canonical_payload` LONGTEXT NOT NULL,
    `payload_schema_version` VARCHAR(64) NOT NULL,
    `action_status` VARCHAR(64) NOT NULL,
    `expires_at` DATETIME(6) NULL,
    `anonymized_at` DATETIME(6) NULL,
    `attempt_hash` CHAR(64) NOT NULL,
    `index_pending` SMALLINT NOT NULL,
    CONSTRAINT `nfs_submissions_u0` UNIQUE (`uuid`),
    CONSTRAINT `nfs_submissions_u1` UNIQUE (`form_id`, `attempt_hash`),
    CONSTRAINT `#__nfs_submissions_form` FOREIGN KEY (`form_id`) REFERENCES `#__nicode_form_studio_forms` (`id`),
    INDEX `nfs_submissions_i0` (`received_at`, `id`),
    INDEX `nfs_submissions_i1` (`form_id`, `received_at`, `id`),
    INDEX `nfs_submissions_i2` (`form_id`, `state`, `received_at`, `id`),
    INDEX `nfs_submissions_i3` (`form_version_id`, `received_at`, `id`),
    INDEX `nfs_submissions_i4` (`user_id`, `received_at`, `id`),
    INDEX `nfs_submissions_i5` (`action_status`, `received_at`, `id`),
    INDEX `nfs_submissions_i6` (`expires_at`, `id`),
    INDEX `nfs_submissions_i7` (`index_pending`, `id`),
    INDEX `nfs_submissions_i8` (`form_id`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `#__nicode_form_studio_submission_index` (
    `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `submission_id` BIGINT NOT NULL,
    `form_id` BIGINT NOT NULL,
    `form_version_id` BIGINT NOT NULL,
    `field_uuid` CHAR(36) NOT NULL,
    `instance_path` VARCHAR(4735) NOT NULL DEFAULT '',
    `instance_hash` CHAR(64) NOT NULL DEFAULT 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    `value_type` VARCHAR(64) NOT NULL,
    `value_keyword` VARBINARY(1020) NULL,
    `value_text` LONGTEXT NULL,
    `value_integer` BIGINT NULL,
    `value_decimal` DECIMAL(38,12) NULL,
    `value_boolean` SMALLINT NULL,
    `value_date` DATE NULL,
    `value_datetime` DATETIME(6) NULL,
    `ordinal` INTEGER NOT NULL,
    CONSTRAINT `nfs_submission_index_u0` UNIQUE (`submission_id`, `field_uuid`, `instance_hash`, `ordinal`),
    CONSTRAINT `#__nfs_submission_index_sub` FOREIGN KEY (`submission_id`) REFERENCES `#__nicode_form_studio_submissions` (`id`),
    INDEX `nfs_submission_index_i0` (`form_id`, `field_uuid`, `value_keyword`, `submission_id`),
    INDEX `nfs_submission_index_i1` (`form_id`, `field_uuid`, `value_integer`, `submission_id`),
    INDEX `nfs_submission_index_i2` (`form_id`, `field_uuid`, `value_decimal`, `submission_id`),
    INDEX `nfs_submission_index_i3` (`form_id`, `field_uuid`, `value_boolean`, `submission_id`),
    INDEX `nfs_submission_index_i4` (`form_id`, `field_uuid`, `value_date`, `submission_id`),
    INDEX `nfs_submission_index_i5` (`form_id`, `field_uuid`, `value_datetime`, `submission_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `#__nicode_form_studio_submission_files` (
    `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `uuid` CHAR(36) NOT NULL,
    `submission_id` BIGINT NOT NULL,
    `field_uuid` CHAR(36) NOT NULL,
    `instance_path` VARCHAR(4735) NOT NULL DEFAULT '',
    `instance_hash` CHAR(64) NOT NULL DEFAULT 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    `provider` VARCHAR(64) NOT NULL,
    `storage_key` VARCHAR(255) NOT NULL,
    `original_name` VARCHAR(255) NOT NULL,
    `mime` VARCHAR(255) NOT NULL,
    `size_bytes` BIGINT NOT NULL,
    `checksum` CHAR(64) NOT NULL,
    `created_at` DATETIME(6) NOT NULL,
    CONSTRAINT `nfs_submission_files_u0` UNIQUE (`uuid`),
    CONSTRAINT `nfs_submission_files_u1` UNIQUE (`provider`, `storage_key`),
    CONSTRAINT `#__nfs_submission_files_sub` FOREIGN KEY (`submission_id`) REFERENCES `#__nicode_form_studio_submissions` (`id`),
    INDEX `nfs_submission_files_i0` (`submission_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `#__nicode_form_studio_upload_staging` (
    `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `form_id` BIGINT NOT NULL,
    `provider` VARCHAR(64) NOT NULL,
    `storage_key` VARCHAR(255) NOT NULL,
    `owner_token` CHAR(64) NOT NULL,
    `state` VARCHAR(64) NOT NULL,
    `created_at` DATETIME(6) NOT NULL,
    `expires_at` DATETIME(6) NOT NULL,
    `size_bytes` BIGINT NULL,
    `checksum` CHAR(64) NULL,
    CONSTRAINT `nfs_upload_staging_u0` UNIQUE (`provider`, `storage_key`),
    INDEX `nfs_upload_staging_i0` (`expires_at`, `id`),
    INDEX `nfs_upload_staging_i1` (`form_id`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `#__nicode_form_studio_action_runs` (
    `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `submission_id` BIGINT NOT NULL,
    `action_uuid` CHAR(36) NOT NULL,
    `action_type` VARCHAR(64) NOT NULL,
    `attempt` INTEGER NOT NULL,
    `state` VARCHAR(64) NOT NULL,
    `created_at` DATETIME(6) NOT NULL,
    `started_at` DATETIME(6) NULL,
    `finished_at` DATETIME(6) NULL,
    `result_code` VARCHAR(64) NULL,
    `next_retry_at` DATETIME(6) NULL,
    `lease_token` CHAR(64) NULL,
    `lease_until` DATETIME(6) NULL,
    `revision` BIGINT NOT NULL,
    CONSTRAINT `nfs_action_runs_u0` UNIQUE (`submission_id`, `action_uuid`, `attempt`),
    CONSTRAINT `#__nfs_action_runs_sub` FOREIGN KEY (`submission_id`) REFERENCES `#__nicode_form_studio_submissions` (`id`),
    INDEX `nfs_action_runs_i0` (`state`, `next_retry_at`, `id`),
    INDEX `nfs_action_runs_i1` (`submission_id`, `id`),
    INDEX `nfs_action_runs_i2` (`created_at`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `#__nicode_form_studio_submission_notes` (
    `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `submission_id` BIGINT NOT NULL,
    `created_by` BIGINT NOT NULL,
    `created_at` DATETIME(6) NOT NULL,
    `body` LONGTEXT NOT NULL,
    CONSTRAINT `#__nfs_submission_notes_sub` FOREIGN KEY (`submission_id`) REFERENCES `#__nicode_form_studio_submissions` (`id`),
    INDEX `nfs_submission_notes_i0` (`submission_id`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `#__nicode_form_studio_technical_log` (
    `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `correlation_id` CHAR(36) NOT NULL,
    `level` VARCHAR(64) NOT NULL,
    `event_type` VARCHAR(64) NOT NULL,
    `form_uuid` CHAR(36) NULL,
    `version_id` BIGINT NULL,
    `submission_uuid` CHAR(36) NULL,
    `action_run_id` BIGINT NULL,
    `job_id` BIGINT NULL,
    `created_at` DATETIME(6) NOT NULL,
    INDEX `nfs_technical_log_i0` (`created_at`, `id`),
    INDEX `nfs_technical_log_i1` (`correlation_id`, `id`),
    INDEX `nfs_technical_log_i2` (`level`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `#__nicode_form_studio_audit_log` (
    `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `correlation_id` CHAR(36) NOT NULL,
    `actor_id` BIGINT NOT NULL,
    `event_type` VARCHAR(64) NOT NULL,
    `form_id` BIGINT NULL,
    `submission_uuid` CHAR(36) NULL,
    `created_at` DATETIME(6) NOT NULL,
    `safe_metadata` LONGTEXT NOT NULL,
    INDEX `nfs_audit_log_i0` (`form_id`, `created_at`, `id`),
    INDEX `nfs_audit_log_i1` (`event_type`, `created_at`, `id`),
    INDEX `nfs_audit_log_i2` (`form_id`, `submission_uuid`, `id`),
    INDEX `nfs_audit_log_i3` (`created_at`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `#__nicode_form_studio_jobs` (
    `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `uuid` CHAR(36) NOT NULL,
    `job_type` VARCHAR(64) NOT NULL,
    `form_id` BIGINT NULL,
    `creator_id` BIGINT NOT NULL,
    `state` VARCHAR(64) NOT NULL,
    `parameters` LONGTEXT NOT NULL,
    `cursor_data` LONGTEXT NOT NULL,
    `processed` BIGINT NOT NULL,
    `failed` BIGINT NOT NULL,
    `created_at` DATETIME(6) NOT NULL,
    `started_at` DATETIME(6) NULL,
    `finished_at` DATETIME(6) NULL,
    `available_at` DATETIME(6) NOT NULL,
    `lease_token` CHAR(64) NULL,
    `lease_until` DATETIME(6) NULL,
    `revision` BIGINT NOT NULL,
    `result_code` VARCHAR(64) NULL,
    `artifact_key` VARCHAR(255) NULL,
    `expires_at` DATETIME(6) NULL,
    CONSTRAINT `nfs_jobs_u0` UNIQUE (`uuid`),
    INDEX `nfs_jobs_i0` (`state`, `available_at`, `id`),
    INDEX `nfs_jobs_i1` (`lease_until`, `id`),
    INDEX `nfs_jobs_i2` (`creator_id`, `created_at`, `id`),
    INDEX `nfs_jobs_i3` (`form_id`, `job_type`, `state`, `id`),
    INDEX `nfs_jobs_i4` (`job_type`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `#__nicode_form_studio_saved_views` (
    `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `uuid` CHAR(36) NOT NULL,
    `owner_id` BIGINT NOT NULL,
    `form_id` BIGINT NULL,
    `name` VARCHAR(255) NOT NULL,
    `shared` SMALLINT NOT NULL,
    `query_spec` LONGTEXT NOT NULL,
    `columns_spec` LONGTEXT NOT NULL,
    `sort_spec` LONGTEXT NOT NULL,
    CONSTRAINT `nfs_saved_views_u0` UNIQUE (`uuid`),
    INDEX `nfs_saved_views_i0` (`owner_id`, `form_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `#__nicode_form_studio_rate_limits` (
    `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `scope_hash` CHAR(64) NOT NULL,
    `window_start` DATETIME(6) NOT NULL,
    `expires_at` DATETIME(6) NOT NULL,
    `attempts` BIGINT NOT NULL,
    CONSTRAINT `nfs_rate_limits_u0` UNIQUE (`scope_hash`, `window_start`),
    INDEX `nfs_rate_limits_i0` (`expires_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE IF NOT EXISTS `#__nicode_form_studio_attempts` (
    `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `attempt_hash` CHAR(64) NOT NULL,
    `form_id` BIGINT NOT NULL,
    `form_version_id` BIGINT NOT NULL,
    `request_hash` CHAR(64) NOT NULL,
    `state` VARCHAR(64) NOT NULL,
    `response` LONGTEXT NULL,
    `submission_uuid` CHAR(36) NULL,
    `created_at` DATETIME(6) NOT NULL,
    `expires_at` DATETIME(6) NOT NULL,
    CONSTRAINT `nfs_attempts_u0` UNIQUE (`form_id`, `attempt_hash`),
    INDEX `nfs_attempts_i0` (`expires_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
