<?php
declare(strict_types=1);

/** Build reviewed portable install DDL. Never executed from an application request. */
require dirname(__DIR__) . '/src/lib_nicode_form_studio/autoload.php';
$tables = Nicode\FormStudio\Infrastructure\Database\SchemaDefinition::tables();

foreach (['mysql', 'postgresql'] as $dialect) {
    $quote = $dialect === 'mysql' ? '`' : '"';
    $q = static fn (string $name): string => $quote . $name . $quote;
    $sql = "-- Generated by php tools/schema.php; schema 1.0.0. UTC timestamps, no zero dates.\n";
    foreach ($tables as $name => $table) {
        $full = '#__nicode_form_studio_' . $name;
        $lines = [$q('id') . ($dialect === 'mysql' ? ' BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY' : ' BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY')];
        foreach ($table['columns'] as $column => $type) {
            $sqlType = Nicode\FormStudio\Infrastructure\Database\SchemaDefinition::columnSqlType($column, $type, $dialect === 'postgresql');
            $default = match ($column) { 'instance_path' => " DEFAULT ''", 'instance_hash' => " DEFAULT '" . hash('sha256', '') . "'", default => '' };
            $lines[] = $q($column) . ' ' . $sqlType . (str_ends_with($type, '!') ? ' NOT NULL' : ' NULL') . $default;
        }
        foreach ($table['unique'] ?? [] as $i => $columns) { $lines[] = 'CONSTRAINT ' . $q(($dialect === 'postgresql' ? '#__' : '') . 'nfs_' . $name . '_u' . $i) . ' UNIQUE (' . implode(', ', array_map($q, $columns)) . ')'; }
        if ($table['form_fk'] ?? false) { $lines[] = 'CONSTRAINT ' . $q('#__nfs_' . $name . '_form') . ' FOREIGN KEY (' . $q('form_id') . ') REFERENCES ' . $q('#__nicode_form_studio_forms') . ' (' . $q('id') . ')'; }
        if ($table['submission_fk'] ?? false) { $lines[] = 'CONSTRAINT ' . $q('#__nfs_' . $name . '_sub') . ' FOREIGN KEY (' . $q('submission_id') . ') REFERENCES ' . $q('#__nicode_form_studio_submissions') . ' (' . $q('id') . ')'; }
        if ($dialect === 'mysql') {
            foreach ($table['indexes'] ?? [] as $i => $columns) { $lines[] = 'INDEX ' . $q('nfs_' . $name . '_i' . $i) . ' (' . implode(', ', array_map($q, $columns)) . ')'; }
        }
        $sql .= '\nCREATE TABLE IF NOT EXISTS ' . $q($full) . " (\n    " . implode(",\n    ", $lines) . "\n)" . ($dialect === 'mysql' ? ' ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin' : '') . ";\n";
        if ($dialect === 'postgresql') {
            foreach ($table['indexes'] ?? [] as $i => $columns) { $sql .= 'CREATE INDEX IF NOT EXISTS ' . $q('#__nfs_' . $name . '_i' . $i) . ' ON ' . $q($full) . ' (' . implode(', ', array_map($q, $columns)) . ");\n"; }
        }
    }
    $sql = str_replace('\\nCREATE', "\nCREATE", $sql);
    $directory = dirname(__DIR__) . '/src/com_nicode_form_studio/administrator/sql/' . $dialect;
    file_put_contents($directory . '/install.sql', $sql);
    file_put_contents($directory . '/updates/1.0.0.sql', $sql);
    $uninstall = "-- Explicit purge only; the installer must not run this for preserve-data mode.\n";
    foreach (array_reverse(array_keys($tables)) as $name) { $uninstall .= 'DROP TABLE IF EXISTS ' . $q('#__nicode_form_studio_' . $name) . ";\n"; }
    file_put_contents($directory . '/purge.sql', $uninstall);
}
echo count($tables) . " tables generated for MySQL/MariaDB and PostgreSQL.\n";
